matrix:
  include:
    - language: python
      python: '2.7'
      before_script:
        - pip install docker
        - pip install molecule
      script:
        - './ci/main_molecule_build.sh'
    - language: python
      python: '3.6'
      before_script:
        - pip install docker
        - pip install molecule
      script:
        - './ci/main_molecule_build.sh'
    - language: java
      jdk: oraclejdk8
      script:
        - './ci/main_java_build.sh'
    - language: java
      jdk: openjdk8
      script:
        - './ci/main_java_build.sh'
branches:
   only:
   - master
notifications:
   email: false
