---
- name: Converge
  hosts: all

  pre_tasks:
    - name: create test user
      become: true
      user:
        name: '{{ item }}'
        state: present
        home: '/home/{{ item }}'
        createhome: true
      with_items:
        - test_usr

  roles:
    - role: agilix.atom
      agilix_atom_become_users:
        - atom_packages:
            - behave-step
          username: test_usr
