---
- name: Converge
  hosts: all

  pre_tasks:
    - name: create test user
      become: true
      user:
        name: '{{ item }}'
        state: present
        home: '/home/{{ item }}'
        createhome: yes
      with_items:
        - test_usr

  roles:
    - role: agilix.atom
