---

- name: (Debian) Get the installed Atom version
  changed_when: false
  failed_when: false
  shell: "dpkg -s atom | grep '^Version:' | cut -d ' ' -f 2"
  register: atom_installed_version_return

- name: (Debian) Uninstall Atom if needed
  apt:
    name: atom
    state: absent
  when: "atom_installed_ver != atom_ver"
