# Common configuration shared between all applications
configserver:
    name: Docker JHipster Registry
    status: Connected to Consul running in Rancher

jhipster:
    security:
        authentication:
            jwt:
                base64-secret: NDM5YWRiNjNkNGVhZmU4NjkzNzg5M2U4M2Q0Mzc1ZDVkYTQ1NGE0NDlhZmNjZWY5YTViZGU2ZjM3YjY4NjIwMmQ2MWUyNzIyMTkzZGNjMmUyY2U1YTQzNmIyN2U4MDg3OWU1Zg==
